"""add daily llm usage

Revision ID: 758d895c43c0
Revises: d6efdef23ede
Create Date: 2026-07-17 14:17:25.457965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '758d895c43c0'
down_revision: Union[str, Sequence[str], None] = 'd6efdef23ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_llm_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_date', 'provider', name='uq_daily_llm_usage_date_provider')
    )
    op.create_index(op.f('ix_daily_llm_usage_provider'), 'daily_llm_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_daily_llm_usage_usage_date'), 'daily_llm_usage', ['usage_date'], unique=False)
    # NOTE: autogenerate also proposed dropping 'ix_users_full_name_trgm' —
    # that's a raw-SQL trigram index (search) that predates SQLModel
    # metadata tracking it, not a real schema drift. Left untouched here;
    # deliberately not reflected in models/user.py.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_llm_usage_usage_date'), table_name='daily_llm_usage')
    op.drop_index(op.f('ix_daily_llm_usage_provider'), table_name='daily_llm_usage')
    op.drop_table('daily_llm_usage')
    # ### end Alembic commands ###
