"""add patient and clinical notes, name search index

Revision ID: 89509bb2d1ed
Revises: c0c03e55fdd2
Create Date: 2026-07-16 23:50:40.129985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89509bb2d1ed'
down_revision: Union[str, Sequence[str], None] = 'c0c03e55fdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: `content` is stored as ciphertext (EncryptedString wraps String at
    # the ORM layer) — the migration declares the underlying DB type directly
    # rather than importing the app's TypeDecorator.
    op.create_table('clinical_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_shared_with_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_booking_id'), 'clinical_notes', ['booking_id'], unique=True)
    op.create_index(op.f('ix_clinical_notes_doctor_id'), 'clinical_notes', ['doctor_id'], unique=False)
    op.create_table('patient_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_notes_booking_id'), 'patient_notes', ['booking_id'], unique=True)
    op.create_index(op.f('ix_patient_notes_patient_profile_id'), 'patient_notes', ['patient_profile_id'], unique=False)
    # ### end Alembic commands ###

    # F10: full-text-ish search on doctor name via ILIKE, backed by a trigram
    # GIN index so substring matches stay fast at 10k-doctor scale.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_users_full_name_trgm ON users USING gin (full_name gin_trgm_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_users_full_name_trgm")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_notes_patient_profile_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_booking_id'), table_name='patient_notes')
    op.drop_table('patient_notes')
    op.drop_index(op.f('ix_clinical_notes_doctor_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_booking_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    # ### end Alembic commands ###
