"""add waitlist, follow_ups, feature_flags tables

Revision ID: 8b8047f1b51b
Revises: c4c5244fcda1
Create Date: 2026-07-17 02:50:44.457044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b8047f1b51b'
down_revision: Union[str, Sequence[str], None] = 'c4c5244fcda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'notified', 'deferred', name='followupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_booking_id'), 'follow_ups', ['booking_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_doctor_id'), 'follow_ups', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_patient_profile_id'), 'follow_ups', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_index(op.f('ix_follow_ups_target_date'), 'follow_ups', ['target_date'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_location_id', sa.Uuid(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'holding', 'expired', 'booked', 'cancelled', name='waitliststatus'), nullable=False),
    sa.Column('hold_booking_id', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_location_id'], ['clinic_locations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['hold_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'clinic_location_id', 'start_time_utc', 'patient_profile_id', 'status', name='uq_waitlist_entries_slot_profile_status')
    )
    op.create_index(op.f('ix_waitlist_entries_clinic_location_id'), 'waitlist_entries', ['clinic_location_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_doctor_id'), 'waitlist_entries', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_patient_profile_id'), 'waitlist_entries', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_start_time_utc'), 'waitlist_entries', ['start_time_utc'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_status'), 'waitlist_entries', ['status'], unique=False)
    # NOT dropping ix_users_full_name_trgm: autogenerate flags it as "removed"
    # because it's a raw-SQL pg_trgm GIN index (F10 search) that SQLModel's
    # metadata can't represent, not because this migration touches it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_entries_status'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_start_time_utc'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_patient_profile_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_doctor_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_clinic_location_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_follow_ups_target_date'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_patient_profile_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_doctor_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_booking_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###

    # Postgres ENUM types are separate DB objects that op.drop_table() does not
    # remove — drop them explicitly so downgrade is fully reversible.
    bind = op.get_bind()
    for enum_name in ('waitliststatus', 'followupstatus'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
