"""add reviews reminder logs and audit logs

Revision ID: 9133db2c73a5
Revises: 89509bb2d1ed
Create Date: 2026-07-17 00:34:10.386559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9133db2c73a5'
down_revision: Union[str, Sequence[str], None] = '89509bb2d1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('offset', sa.Enum('24h', '1h', name='reminderoffset'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'offset', name='uq_reminder_logs_booking_offset')
    )
    op.create_index(op.f('ix_reminder_logs_booking_id'), 'reminder_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_offset'), 'reminder_logs', ['offset'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('moderation_status', sa.Enum('pending', 'approved', 'rejected', name='reviewmoderationstatus'), nullable=False),
    sa.Column('moderation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_reply', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('doctor_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_doctor_id'), 'reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_reviews_moderation_status'), 'reviews', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_reviews_patient_profile_id'), 'reviews', ['patient_profile_id'], unique=False)
    # NOTE: autogenerate falsely detects ix_users_full_name_trgm as removed —
    # it's a raw op.execute()'d trigram index (F10) that isn't tracked via
    # SQLAlchemy metadata. Left untouched; do not drop/recreate it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_patient_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_moderation_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_doctor_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reminder_logs_offset'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_booking_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
