"""initial schema

Revision ID: c0c03e55fdd2
Revises: 
Create Date: 2026-07-16 23:00:25.469355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0c03e55fdd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization_taxonomy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialization_taxonomy_slug'), 'specialization_taxonomy', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='userrole'), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('specialization_id', sa.Uuid(), nullable=False),
    sa.Column('qualifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consultation_fee', sa.Integer(), nullable=False),
    sa.Column('pmc_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'rejected', name='doctorverificationstatus'), nullable=False),
    sa.Column('verification_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancellation_policy_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_pmc_number'), 'doctor_profiles', ['pmc_number'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_specialization_id'), 'doctor_profiles', ['specialization_id'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_verification_status'), 'doctor_profiles', ['verification_status'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('clinic_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('map_embed_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_locations_city'), 'clinic_locations', ['city'], unique=False)
    op.create_index(op.f('ix_clinic_locations_doctor_id'), 'clinic_locations', ['doctor_id'], unique=False)
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_location_id', sa.Uuid(), nullable=True),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_location_id'], ['clinic_locations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_exceptions_clinic_location_id'), 'availability_exceptions', ['clinic_location_id'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_doctor_id'), 'availability_exceptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_exception_date'), 'availability_exceptions', ['exception_date'], unique=False)
    op.create_table('availability_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_location_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekday'), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_location_id'], ['clinic_locations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_rules_clinic_location_id'), 'availability_rules', ['clinic_location_id'], unique=False)
    op.create_index(op.f('ix_availability_rules_doctor_id'), 'availability_rules', ['doctor_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_location_id', sa.Uuid(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'confirmed', 'completed', 'cancelled', 'rejected', 'expired', 'no_show', name='bookingstatus'), nullable=False),
    sa.Column('source', sa.Enum('user', 'system_waitlist', name='bookingsource'), nullable=False),
    sa.Column('fee_charged', sa.Integer(), nullable=False),
    sa.Column('address_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rescheduled_from_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_by', sa.Enum('patient', 'doctor', 'admin', name='cancelledby'), nullable=True),
    sa.Column('cancelled_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_location_id'], ['clinic_locations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_clinic_location_id'), 'bookings', ['clinic_location_id'], unique=False)
    op.create_index(op.f('ix_bookings_doctor_id'), 'bookings', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_bookings_expires_at'), 'bookings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_patient_profile_id'), 'bookings', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_time_utc'), 'bookings', ['start_time_utc'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('uq_bookings_active_slot', 'bookings', ['doctor_id', 'clinic_location_id', 'start_time_utc'], unique=True, postgresql_where=sa.text("status IN ('draft', 'pending', 'confirmed')"))
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('in_app', 'email', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_booking_id'), 'notifications', ['booking_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_booking_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_bookings_active_slot', table_name='bookings', postgresql_where=sa.text("status IN ('draft', 'pending', 'confirmed')"))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time_utc'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_profile_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_expires_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_doctor_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_clinic_location_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_availability_rules_doctor_id'), table_name='availability_rules')
    op.drop_index(op.f('ix_availability_rules_clinic_location_id'), table_name='availability_rules')
    op.drop_table('availability_rules')
    op.drop_index(op.f('ix_availability_exceptions_exception_date'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_doctor_id'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_clinic_location_id'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_clinic_locations_doctor_id'), table_name='clinic_locations')
    op.drop_index(op.f('ix_clinic_locations_city'), table_name='clinic_locations')
    op.drop_table('clinic_locations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_doctor_profiles_verification_status'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialization_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_pmc_number'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_specialization_taxonomy_slug'), table_name='specialization_taxonomy')
    op.drop_table('specialization_taxonomy')
    # ### end Alembic commands ###

    # Postgres ENUM types are separate DB objects that op.drop_table() does not
    # remove — drop them explicitly so downgrade is fully reversible.
    bind = op.get_bind()
    for enum_name in (
        'userrole',
        'doctorverificationstatus',
        'weekday',
        'bookingstatus',
        'bookingsource',
        'cancelledby',
        'notificationchannel',
        'notificationstatus',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
