"""add account deletion columns

Revision ID: c33ae8bc0b01
Revises: fd1b4822fbf2
Create Date: 2026-07-17 15:06:27.036093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c33ae8bc0b01'
down_revision: Union[str, Sequence[str], None] = 'fd1b4822fbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))
    # Indexed because the purge sweep's only query is a range scan over it
    # (`WHERE purge_after <= now() AND purged_at IS NULL`), running against
    # the full users table on every daily tick.
    op.create_index(op.f('ix_users_purge_after'), 'users', ['purge_after'], unique=False)

    # NOTE: autogenerate also proposed dropping 'ix_users_full_name_trgm' —
    # a raw-SQL trigram index backing doctor search, not tracked in SQLModel
    # metadata and not real drift. Left untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_purge_after'), table_name='users')
    op.drop_column('users', 'purged_at')
    op.drop_column('users', 'purge_after')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
