"""add agent sessions and messages

Revision ID: c4c5244fcda1
Revises: 9133db2c73a5
Create Date: 2026-07-17 01:52:43.442833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4c5244fcda1'
down_revision: Union[str, Sequence[str], None] = '9133db2c73a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_patient_profile_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_active_patient_profile_id'), 'agent_sessions', ['active_patient_profile_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    # Note: `content` is stored as ciphertext (EncryptedString wraps String at
    # the ORM layer) — the migration declares the underlying DB type directly
    # rather than importing the app's TypeDecorator (matches the note tables' pattern).
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='agentrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    # NOT dropping ix_users_full_name_trgm: autogenerate flags it as "removed"
    # because it's a raw-SQL pg_trgm GIN index (F10 search) that SQLModel's
    # metadata can't represent, not because this migration touches it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_active_patient_profile_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###

    # Postgres ENUM types are separate DB objects that op.drop_table() does not
    # remove — drop them explicitly so downgrade is fully reversible (same
    # pattern as the initial migration).
    sa.Enum(name='agentrole').drop(op.get_bind(), checkfirst=True)
