"""add medical history, notification preference, dead letter jobs

Revision ID: d6efdef23ede
Revises: 8b8047f1b51b
Create Date: 2026-07-17 10:55:27.086927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6efdef23ede'
down_revision: Union[str, Sequence[str], None] = '8b8047f1b51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: medical_histories' encrypted columns (blood_group, allergies,
    # medications, chronic_conditions, surgeries) are stored as ciphertext
    # (EncryptedString wraps String at the ORM layer) — declared here as the
    # underlying DB type directly, same convention as clinical_notes.content.
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_jobs_job_type'), 'dead_letter_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_dead_letter_jobs_reference_id'), 'dead_letter_jobs', ['reference_id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('blood_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chronic_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('surgeries', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_profile_id', 'version', name='uq_medical_histories_profile_version')
    )
    op.create_index(op.f('ix_medical_histories_patient_profile_id'), 'medical_histories', ['patient_profile_id'], unique=False)
    op.add_column('notifications', sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_notifications_provider_message_id'), 'notifications', ['provider_message_id'], unique=False)
    # Unlike enum columns declared inline on op.create_table(...), ALTER
    # TABLE ADD COLUMN does not implicitly CREATE TYPE — do it explicitly.
    notification_preference_enum = sa.Enum('default', 'sms_first', name='notificationpreference')
    notification_preference_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'notification_preference',
            notification_preference_enum,
            nullable=False,
            server_default='default',
        ),
    )
    # NOTE: autogenerate falsely detects ix_users_full_name_trgm as removed —
    # it's a raw op.execute()'d trigram index (F10) that isn't tracked via
    # SQLAlchemy metadata. Left untouched; do not drop/recreate it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preference')
    sa.Enum(name='notificationpreference').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_notifications_provider_message_id'), table_name='notifications')
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'provider_message_id')
    op.drop_index(op.f('ix_medical_histories_patient_profile_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_dead_letter_jobs_reference_id'), table_name='dead_letter_jobs')
    op.drop_index(op.f('ix_dead_letter_jobs_job_type'), table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    # ### end Alembic commands ###
